robot_cfg:
   kinematics:
    usd_path: robot/stretch_description/stretch_description_RE2V0_tool_dex_wrist.usd
    usd_robot_root: /robot
    isaac_usd_path: 
    use_usd_kinematics: False
   
    usd_flip_joint_limits: []
    urdf_path: robot/stretch_description/stretch_xy.urdf
    asset_root_path: robot/stretch_description/
    base_link: base_ground
    ee_link: link_grasp_center
    link_names: null
    lock_joints: null
    extra_links: null
    usd_flip_joints: ["joint_wrist_yaw"]
    usd_flip_joints: {
    "joint_wrist_yaw": "Z",
  
    }
    collision_link_names: ["base_link","link_mast","link_arm_l4","link_arm_l3","link_arm_l2","link_arm_l1","link_arm_l0","link_gripper_finger_left","link_gripper_finger_right"]
    #collision_link_names: ["link_arm_l4","link_arm_l3","link_arm_l2","link_arm_l1","link_arm_l0","link_gripper_finger_left","link_gripper_finger_right"]
    collision_spheres:
      base_link:
        - "center": [0.0, 0.12, 0.06]
          "radius": 0.12
        - "center": [0.0, -0.12, 0.06]
          "radius": 0.12
        - "center": [0.0, 0.04, 0.06]
          "radius": 0.12
        - "center": [0.0, -0.04, 0.06]
          "radius": 0.12
        - "center": [-0.24, -0.12, 0.06]
          "radius": 0.12
        - "center": [-0.24, 0.12, 0.06]
          "radius": 0.12
        - "center": [-0.24, -0.04, 0.06]
          "radius": 0.12
        - "center": [-0.16, -0.12, 0.06]
          "radius": 0.12
        - "center": [-0.08, -0.12, 0.06]
          "radius": 0.12
        - "center": [-0.08, 0.12, 0.06]
          "radius": 0.12
        - "center": [-0.16, 0.12, 0.06]
          "radius": 0.12
      link_mast:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.1
        - "center": [0.0, 1.3, 0.0]
          "radius": 0.1
        - "center": [0.0, 0.081, 0.0]
          "radius": 0.1
        - "center": [0.0, 0.162, 0.0]
          "radius": 0.1
        - "center": [0.0, 0.244, 0.0]
          "radius": 0.1
        - "center": [0.0, 0.325, 0.0]
          "radius": 0.1
        - "center": [0.0, 0.406, 0.0]
          "radius": 0.1
        - "center": [0.0, 0.487, 0.0]
          "radius": 0.1
        - "center": [0.0, 0.569, 0.0]
          "radius": 0.1
        - "center": [0.0, 0.65, 0.0]
          "radius": 0.1
        - "center": [0.0, 0.731, 0.0]
          "radius": 0.1
        - "center": [0.0, 0.812, 0.0]
          "radius": 0.1
        - "center": [0.0, 0.894, 0.0]
          "radius": 0.1
        - "center": [0.0, 0.975, 0.0]
          "radius": 0.1
        - "center": [0.0, 1.056, 0.0]
          "radius": 0.1
        - "center": [0.0, 1.137, 0.0]
          "radius": 0.1
        - "center": [0.0, 1.219, 0.0]
          "radius": 0.1
      link_arm_l0:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.06tretch_descr
          "radius": 0.06
        - "center": [0.0, 0.0, -0.087]
          "radius": 0.06
      link_arm_l1:
        - "center": [0.0, 0.0, -0.13]
          "radius": 0.06
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.06
        - "center": [0.0, 0.0, -0.087]
          "radius": 0.06
        - "center": [0.0, 0.0, -0.043]
          "radius": 0.06
      link_arm_l3:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.06
        - "center": [0.0, 0.0, -0.13]
          "radius": 0.06
        - "center": [0.0, 0.0, -0.043]
          "radius": 0.06
        - "center": [0.0, 0.0, -0.087]
          "radius": 0.06
      link_arm_l2:
        - "center": [0.0, 0.0, -0.13]
          "radius": 0.06
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.06
        - "center": [0.0, 0.0, -0.087]
          "radius": 0.06
        - "center": [0.0, 0.0, -0.043]
          "radius": 0.06
      link_arm_l4:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.06
        - "center": [0.0, 0.0, -0.13]
          "radius": 0.06
        - "center": [0.0, 0.0, -0.043]
          "radius": 0.06
        - "center": [0.0, 0.0, -0.087]
          "radius": 0.06
      link_gripper_finger_left:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.03
        - "center": [0.169, -0.0, 0.0]
          "radius": 0.03
        - "center": [0.028, -0.0, 0.0]
          "radius": 0.03
        - "center": [0.056, -0.0, 0.0]
          "radius": 0.03
        - "center": [0.085, -0.0, 0.0]
          "radius": 0.03
        - "center": [0.113, -0.0, 0.0]
          "radius": 0.03
        - "center": [0.141, -0.0, 0.0]
          "radius": 0.03
      link_gripper_finger_right:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.03
        - "center": [-0.179, 0.0, 0.005]
          "radius": 0.03
        - "center": [-0.03, 0.0, 0.001]
          "radius": 0.03
        - "center": [-0.06, 0.0, 0.002]
          "radius": 0.03
        - "center": [-0.09, 0.0, 0.002]
          "radius": 0.03
        - "center": [-0.12, 0.0, 0.003]
          "radius": 0.03
        - "center": [-0.149, 0.0, 0.004]
          "radius": 0.03


    collision_sphere_buffer: 0.005
    extra_collision_spheres: {}
    self_collision_ignore: {
      #rotation_link: [translation_link],
      base_link: [rotation_link, translation_link, link_mast,link_arm_l4,link_arm_l3,link_arm_l2,link_arm_l1,link_arm_l0,link_gripper_finger_left,link_gripper_finger_right], #[link_ground, link_mast, link_arm_l4, link_arm_l3, link_arm_l2, link_arm_l1, link_arm_l0],
      link_mast: [link_arm_l4,link_arm_l3,link_arm_l2,link_arm_l1,link_arm_l0,link_gripper_finger_left,link_gripper_finger_right],
      link_arm_l4: [link_arm_l3,link_arm_l2,link_arm_l1,link_arm_l0,link_gripper_finger_left,link_gripper_finger_right],
      link_arm_l3: [link_arm_l2,link_arm_l1,link_arm_l0,link_gripper_finger_left,link_gripper_finger_right],
      link_arm_l2: [link_arm_l1,link_arm_l0,link_gripper_finger_left,link_gripper_finger_right],
      link_arm_l1: [link_arm_l0,link_gripper_finger_left,link_gripper_finger_right],
      link_arm_l0: [link_gripper_finger_left,link_gripper_finger_right],
      link_gripper_finger_left: [link_gripper_finger_right],
      

      # link_ground: [link_mast,link_arm_l4,link_arm_l3, link_arm_l2, link_arm_l1, link_arm_l0],
      # link_mast: [link_arm_l4,link_arm_l3, link_arm_l2, link_arm_l1, link_arm_l0 ],
      # link_arm_l4: [link_arm_l3, link_arm_l2, link_arm_l1, link_arm_l0],
      # link_arm_l3: [link_arm_l2, link_arm_l1, link_arm_l0],
      # link_arm_l2: [link_arm_l1, link_arm_l0],
      # link_arm_l1: [link_arm_l0],

      }
    self_collision_buffer: {'rotation_link': 0, 'translation_link': 0, 'base_link': 0, "link_mast": 0,"link_arm_l4": 0 ,"link_arm_l3": 0, "link_arm_l2": 0, "link_arm_l1": 0, "link_arm_l0": 0,"link_gripper_finger_left": 0,"link_gripper_finger_right": 0
     
      } 
      
    use_global_cumul: True
    mesh_link_names: null # List[str]

    cspace:
      joint_names: [
        "base_x","base_y", "base_z", "joint_lift","joint_arm_l3","joint_arm_l2","joint_arm_l1","joint_arm_l0","joint_wrist_yaw","joint_gripper_finger_right","joint_gripper_finger_left"]
      retract_config: [0, 0, 0, 0.5,0.05,0.05,0.05,0.05,0,0,0]
      null_space_weight: [1,1,1,1,1,1,1,1,1,1,1]
      cspace_distance_weight: [1,1,1,1,1,1,1,1,1,1,1]
      max_acceleration: 15.0 #15.0
      max_jerk: 500.0
